config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    # get 'search' => 'books#search'
  end

  resources :groups do
    get "join" => "groups#join"
    get "leave" => "groups#leave"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end


  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/search' => 'homes#search'
  get 'search' => 'searches#search'
  resources :messages, only: [:create]
  get 'message/:id' => 'messages#show', as: 'message'
  get 'books/search' => 'books#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
  has_many :count_favorited, through: :favorites, source: :user
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
	scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
	scope :created_thisweek, -> { where(:created_at=> 6.day.ago..Time.now) }
	scope :created_lastweek, -> { where(:created_at=> 13.day.ago..7.day.ago) }

	scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }

	def self.book_count
	 (0..6).map { |n| created_days_ago(n).count }.reverse
	end

	is_impressionable counter_cache: true

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

	validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  attachment :group_image, destroy: false

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages
  has_many :user_rooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites
  has_many :favorited_bookd, through: :favorites, source: :book
  has_many :book_comments
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  attachment :profile_image, destroy: false

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/book_comments_controller.rb
class BookCommentsController < ApplicationController
  before_action :authenticate_user!

  def create
    @book = Book.find(params[:book_id])
    @book_comment = @book.book_comments.new(book_comment_params)
    @book_comment.user_id = current_user.id
    @book_comment.book_id = @book.id
    if @book_comment.save
      render :index
    else
      render :error
    end

  end

  def destroy
    @book = Book.find(params[:book_id])
    book_comment = @book.book_comments.find(params[:id])
    book_comment.destroy
    render :index

  end

  private

  def book_comment_params
    params.require(:book_comment).permit(:comment)
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new

    # 閲覧数をカウント
    impressionist(@book, nil, unique: [:session_hash.to_s])
  end

  def index
    # @books = Book.all
    @book = Book.new
    # @books = Book.left_joins(:week_favorites).group(:id).order('count(book_id) desc')
    @books = Book.all.order(params[:sort])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :evaluation, :category)
    # params.require(:book).permit(:title, :body, :created_at)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/book_comments_helper.rb
module BookCommentsHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/book_comments/_comment.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback:'no-image-icon.jpg') %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user_id == current_user.id %>
        <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, class: 'btn btn-danger btn-sm' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

<%= form_with model:[book, book_comment], url:book_book_comments_path(book), local:true do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, rows:5, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/book_comments/_form.html.erb
<%= form_with model:[book, book_comment], url:book_book_comments_path(book), remote: true do |f| %>
  <div class="form-group">
    <%= f.text_area :comment, rows:5, class: 'form-control' %>
  </div>
  <div class="form-group">
    <%= f.submit '送信' %>
  </div>
<% end %>

app/views/book_comments/_index.html.erb
<table>
  <% book.book_comments.each do |book_comment| %>
    <tr>
      <td>
        <%= link_to user_path(book_comment.user) do %>
          <%= attachment_image_tag(book_comment.user, :profile_image, :fill, 50, 50, fallback:'no-image-icon.jpg') %><br>
          <%= book_comment.user.name %>
        <% end %>
      </td>
      <td><%= book_comment.comment %></td>
      <% if book_comment.user_id == current_user.id %>
        <td><%= link_to 'Destroy', book_book_comment_path(book_comment.book_id, book_comment.id), method: :delete, remote: true, class: 'btn btn-danger btn-sm' %></td>
      <% end %>
    </tr>
  <% end %>
</table>

app/views/book_comments/error.js.erb
$("main > .container").prepend("<%= j(render 'layouts/errors', obj: @book_comment) %>");

app/views/book_comments/index.js.erb
$(".book_comment_<%= @book.id %>").html("コメント数: <%= @book.book_comments.count %>");
$("#comments_area").html("<%= j(render 'index', { book: @book }) %>")
$("textarea").val('')