config/routes.rb
Rails.application.routes.draw do
  get 'messages/show'
  devise_for :users

  resources :users,only: [:show,:index,:edit,:update,:destroy] do
    resource :relationships, only: [:create, :destroy]
    get 'followings' => 'relationships#followings', as: 'followings'
    get 'followers' => 'relationships#followers', as: 'followers'
    get 'search' => 'users#search'
  end

  resources :books do
    resource :favorites, only: [:create, :destroy]
    resources :book_comments, only: [:create, :destroy]
    # get 'search' => 'books#search'
  end

  resources :groups do
    get "join" => "groups#join"
    get "leave" => "groups#leave"
    get "new/mail" => "groups#new_mail"
    get "send/mail" => "groups#send_mail"
  end


  root 'homes#top'
  get 'home/about' => 'homes#about'
  get 'home/search' => 'homes#search'
  get 'search' => 'searches#search'
  resources :messages, only: [:create]
  get 'message/:id' => 'messages#show', as: 'message'
  get 'books/search' => 'books#search'

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
	belongs_to :user
	has_many :favorites, dependent: :destroy
  has_many :count_favorited, through: :favorites, source: :user
  has_many :week_favorites, -> { where(created_at: ((Time.current.at_end_of_day - 6.day).at_beginning_of_day)..(Time.current.at_end_of_day)) }, class_name: 'Favorite'
	has_many :book_comments, dependent: :destroy

	validates :title, presence: true
	validates :body, presence: true, length: {maximum: 200}

	def favorited_by?(user)
		favorites.where(user_id: user.id).exists?
	end

	scope :created_today, -> { where(created_at: Time.zone.now.all_day) } # 今日
	scope :created_yesterday, -> { where(created_at: 1.day.ago.all_day) } # 前日
	scope :created_thisweek, -> { where(:created_at=> 6.day.ago..Time.now) }
	scope :created_lastweek, -> { where(:created_at=> 13.day.ago..7.day.ago) }

	scope :created_days_ago, ->(n) { where(created_at: n.days.ago.all_day) }

	def self.book_count
	 (0..6).map { |n| created_days_ago(n).count }.reverse
	end

	is_impressionable counter_cache: true

end

app/models/book_comment.rb
class BookComment < ApplicationRecord

  belongs_to :user
  belongs_to :book

	validates :comment, presence: true

end

app/models/favorite.rb
class Favorite < ApplicationRecord

  belongs_to :user
  belongs_to :book

end

app/models/group.rb
class Group < ApplicationRecord

  has_many :group_users, dependent: :destroy
  has_many :users, through: :group_users

  attachment :group_image, destroy: false

end

app/models/group_user.rb
class GroupUser < ApplicationRecord

  belongs_to :user
  belongs_to :group

end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/models/relationship.rb
class Relationship < ApplicationRecord

  belongs_to :follower, class_name: "User"
  belongs_to :followed, class_name: "User"

end

app/models/room.rb
class Room < ApplicationRecord

  has_many :messages
  has_many :user_rooms

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :books
  has_many :favorites
  has_many :favorited_bookd, through: :favorites, source: :book
  has_many :book_comments
  has_many :groups, through: :group_users
  has_many :group_users
  has_many :user_rooms, dependent: :destroy
  has_many :messages, dependent: :destroy

  attachment :profile_image, destroy: false

  has_many :relationships, class_name: "Relationship", foreign_key: "follower_id", dependent: :destroy
  has_many :reverse_of_relationships, class_name: "Relationship", foreign_key: "followed_id", dependent: :destroy

  has_many :followings, through: :relationships, source: :followed
  has_many :followers, through: :reverse_of_relationships, source: :follower

  validates :name, length: {maximum: 20, minimum: 2}, uniqueness: true
  validates :introduction, length: {maximum: 50}

  def follow(user_id)
    relationships.create(followed_id: user_id)
  end

  def unfollow(user_id)
    relationships.find_by(followed_id: user_id).destroy
  end

  def following?(user)
    followings.include?(user)
  end

end

app/models/user_room.rb
class UserRoom < ApplicationRecord

  belongs_to :user
  belongs_to :room

end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @book = Book.find(params[:id])
    @book_comment = BookComment.new

    # 閲覧数をカウント
    impressionist(@book, nil, unique: [:session_hash.to_s])
  end

  def index
    # @books = Book.all
    @book = Book.new
    # @books = Book.left_joins(:week_favorites).group(:id).order('count(book_id) desc')
    @books = Book.all.order(params[:sort])
  end

  def create
    @book = Book.new(book_params)
    @book.user_id = current_user.id
    if @book.save
      redirect_to book_path(@book), notice: "You have created book successfully."
    else
      @books = Book.all
      render 'index'
    end
  end

  def edit
  end

  def update
    if @book.update(book_params)
      redirect_to book_path(@book), notice: "You have updated book successfully."
    else
      render "edit"
    end
  end

  def destroy
    @book.destroy
    redirect_to books_path
  end

  private

  def book_params
    params.require(:book).permit(:title, :body, :evaluation, :category)
    # params.require(:book).permit(:title, :body, :created_at)
  end

  def ensure_correct_user
    @book = Book.find(params[:id])
    unless @book.user_id == current_user.id
      redirect_to books_path
    end
  end

end

app/controllers/homes_controller.rb
class HomesController < ApplicationController
  def top
  end

  def about
  end

  def search
    @books = Book.where(category: params["category"])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :ensure_correct_user, only: [:edit, :update, :destroy]

  def show
    @user = User.find(params[:id])
    @books = @user.books
    @today_book = @books.created_today
    @yesterday_book = @books.created_yesterday
    @tthisweek_book = @books.created_thisweek
    @lastweek_book = @books.created_lastweek
    @ratio_today = ratio(@today_book.count, @yesterday_book.count)
    @ratio_week = ratio(@tthisweek_book.count, @lastweek_book.count)
    @book = Book.new
  end

  # 前日・前週比を求める計算式
  def ratio(to, from)
    if from == 0
      return 0
    else
      ret = (to / from.to_f)*100
      return ret
    end
  end

  def index
    @users = User.all
    @book = Book.new
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "You have updated user successfully."
    else
      render "edit"
    end
  end

  def destroy
    @user.destroy
    redirect_to users_path
  end

  def search
    @user = User.find(params[:user_id])
    create_at = params[:date]
    if create_at == ""
      @count_book = 0
    else
      @count_book = @user.books.where(['created_at LIKE ? ', "#{create_at}%"]).count
    end
  end

  private
  def user_params
    params.require(:user).permit(:name, :introduction, :profile_image)
  end

  def ensure_correct_user
    @user = User.find(params[:id])
    unless @user == current_user
      redirect_to user_path(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/group_users_helper.rb
module GroupUsersHelper
end

app/helpers/groups_helper.rb
module GroupsHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/books/_form.html.erb
<%= form_with model:book,local:true do |f| %>
  <div class="form-group">
    <%= f.label :title %>
    <%= f.text_field :title, class: 'form-control book_title' %>
  </div>
  <div class="form-group">
    <%= f.label :opinion %>
    <%= f.text_area :body, class: 'form-control book_body' %>
  </div>
  <div class="form-group">
    <%= f.label :category %>
    <%= f.text_field :category, class: 'form-control book_category' %>
  </div>
  <div class="form-group" id="star">
    <%= f.label :rate %>
    <%= f.hidden_field :evaluation, id: :review_star %>
  </div>
  <script>
    $('#star').raty({
      size:36,
      starOff: '<%= asset_path('star-off.png') %>',
      starOn: '<%= asset_path('star-on.png') %>',
      starHalf: '<%= asset_path('star-half.png') %>',
      scoreName: 'book[evaluation]',
      half: 'true',
    });
  </script>
  <div class="form-group">
    <%= f.submit class: 'btn btn-success' %>
  </div>
<% end %>

app/views/books/_index.html.erb
<table class='table table-hover table-inverse'>
  <thead>
    <tr>
      <th></th>
      <th>Title</th>
      <th>Opinion</th>
      <th>Category</th>
      <th colspan="4"></th>
    </tr>
  </thead>
  <tbody>
    <% books.each do |book| %>
      <tr>
        <td><%= link_to user_path(book.user) do %>
          <%= attachment_image_tag(book.user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %>
          <% end %>
        </td>
        <td><%= link_to book.title, book_path(book), class: "book_#{book.id}" %></td>
        <td><%= book.body %></td>
        <td><%= book.category %></td>
        <td class="favorite_btn_<%= book.id %>"><%= render 'favorites/favorite_btn', book: book %></td>
        <td>コメント数: <%= book.book_comments.count  %></td>
        <td>
          <div id="star-rate-<%= book.id %>">
            <script>
            $('#star-rate-<%= book.id %>').raty({
              size: 36,
              starOff:  '<%= asset_path('star-off.png') %>',
              starOn : '<%= asset_path('star-on.png') %>',
              starHalf: '<%= asset_path('star-half.png') %>',
              half: true,
              readOnly: true,
              score: <%= book.evaluation %>,
            });
            </script>
          </div>
        </td>
        <td>閲覧数：<%= book.impressions_count %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/books/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
  		<h1>Editing Book</h1>
    	<%= render 'layouts/errors', obj: @book %>
      <%= form_with model: @book, local:true do |f| %>
        <div class="form-group">
          <%= f.label :title %>
          <%= f.text_field :title, class: 'form-control book_title' %>
        </div>
        <div class="form-group">
          <%= f.label :opinion %>
          <%= f.text_area :body, class: 'form-control book_body' %>
        </div>
        <div class="form-group">
          <%= f.label :category %>
          <%= f.text_field :category, class: 'form-control book_category' %>
        </div>
        <div class="form-group" id="rate_<%= @book.id %>"></div>
        <script>
          $('#rate_<%= @book.id %>').raty({
            size: 20,
            starOff:  '<%= asset_path('star-off.png') %>',
            starOn : '<%= asset_path('star-on.png') %>',
            starHalf: '<%= asset_path('star-half.png') %>',
            half: true,
            readOnly: true,
            score: <%= @book.evaluation %>,
          });
        </script>
        <div class="form-group">
          <%= f.submit class: 'btn btn-success' %>
        </div>
      <% end %>
  		<%= link_to 'Show', book_path(@book), class: "book_#{@book.id}" %> |
  		<%= link_to 'Back', books_path, class: "back" %>
  </div>
</div>

app/views/books/index.html.erb
<div class='container px-5 px-sm-0'>
  <%= render 'layouts/errors', obj: @book %>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= link_to '新しい順', books_path({sort: "1"}) %>|
      <%= link_to '評価の高い順', books_path({sort: "2"}) %>
      <%= render 'index', books: @books %>
    </div>
  </div>
</div>

app/views/books/show.html.erb
<div class='container'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'users/info', user: @book.user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'form', book: Book.new %>
    </div>
    <div class='col-md-8 offset-md-1'>
  		<h2>Book detail</h2>
  		<table class='table'>
  		  <tr>
  		    <td><%= link_to user_path(@book.user) do %>
            <%= attachment_image_tag(@book.user, :profile_image, :fill, 100, 100, fallback: "no-image-icon.jpg") %><br>
            <%= @book.user.name %>
            <% end %>
          </td>
          <td><%= link_to @book.title, book_path(@book) %></td>
          <td><%= @book.body %></td>
          <td><%= @book.category %></td>
          <td class="favorite_btn_<%= @book.id %>"><%= render 'favorites/favorite_btn', book: @book %></td>
          <td class="book_comment_<%= @book.id %>">コメント数: <%= @book.book_comments.count  %></td>
          <td>
            <div id="star-rate-<%= @book.id %>">
              <script>
              $('#star-rate-<%= @book.id %>').raty({
                size: 36,
                starOff:  '<%= asset_path('star-off.png') %>',
                starOn : '<%= asset_path('star-on.png') %>',
                starHalf: '<%= asset_path('star-half.png') %>',
                half: true,
                readOnly: true,
                score: <%= @book.evaluation %>,
              });
              </script>
            </div>
          </td>
          <td>閲覧数：<%= @book.impressionist_count %></td>
          <% if @book.user == current_user %>
            <td><%= link_to 'Edit', edit_book_path(@book), class: "btn btn-sm btn-success edit_book_#{@book.id}" %></td>
            <td><%= link_to 'Destroy', book_path(@book), method: :delete, data: { confirm: '本当に消しますか？' }, class: "btn btn-sm btn-danger destroy_book_#{@book.id}"%></td>
          <% end %>
        </tr>
      </table>
      <div id="comments_area">
        <!-- 投稿されたコメント一覧をブログの詳細ページに表示するためのrender -->
        <%= render partial: 'book_comments/index', locals: { book: @book } %>
      </div>
      <%= render partial: 'book_comments/form', locals: { book: @book, book_comment: @book.book_comments } %>
    </div>
  </div>
</div>

app/views/users/_count.html.erb
<table class="table table_width table-bordered">
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @today_book.count %></td>
      <td><%= @yesterday_book.count %></td>
      <td><%= (@ratio_today).round %>％</td>
    </tr>
  </tbody>
</table>
<table class="table table_width table-bordered">
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>先週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @tthisweek_book.count %></td>
      <td><%= @lastweek_book.count %></td>
      <td><%= (@ratio_week).round %>％</td>
    </tr>
  </tbody>
</table>

app/views/users/_count1.html.erb
<table class="table table_width table-bordered">
  <thead>
    <tr>
      <th>今日の投稿数</th>
      <th>前日の投稿数</th>
      <th>前日比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @today_book.count %></td>
      <td><%= @yesterday_book.count %></td>
      <td><%= (@ratio_today).round %>％</td>
    </tr>
  </tbody>
</table>
<table class="table table_width table-bordered">
  <thead>
    <tr>
      <th>今週の投稿数</th>
      <th>先週の投稿数</th>
      <th>前週比</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @tthisweek_book.count %></td>
      <td><%= @lastweek_book.count %></td>
      <td><%= (@ratio_week).round %>％</td>
    </tr>
  </tbody>
</table>

app/views/users/_count2.html.erb
<table class="table table_width table-bordered">
  <thead>
    <tr>
      <th>６日前</th>
      <th>５日前</th>
      <th>４日前</th>
      <th>３日前</th>
      <th>２日前</th>
      <th>昨日</th>
      <th>今日</th>
    </tr>
  </thead>
  <tbody>
    <tr>
       <% books.book_count.each do |book| %>
        <th><%= book %></th>
      <% end %>
    </tr>
  </tbody>
</table>

app/views/users/_index.html.erb
<table class='table'>
  <thead>
    <tr>
      <th>image</th>
      <th>name</th>
      <th colspan="6"></th>
    </tr>
  </thead>
  <tbody>
    <% users.each do |user| %>
      <tr>
        <td><%= attachment_image_tag(user, :profile_image, :fill, 50, 50, fallback: "no-image-icon.jpg") %></td>
        <td><%= user.name %></td>
        <td>フォロー数: <%= user.followings.count %></td>
        <td>フォロワー数: <%= user.followers.count %></td>
        <td>
          <% unless user.id == current_user.id %>
            <%= render 'relationships/follow_link', user: user %>
          <% end %>
        </td>
        <td><%= link_to 'Show', user_path(user), class: "user_#{user.id}" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/users/_info.html.erb
<table class='table'>
  <tr><%= attachment_image_tag(user, :profile_image, :fill, 100, 100, fallback: "no_image.jpg") %></tr>
  <tr>
	  <th>name</th>
	  <th><%= user.name %></th>
  </tr>
  <tr>
	  <th>introduction</th>
	  <th><%= user.introduction %></th>
  </tr>
  <tr>
	  <th>follows</th>
	  <th><%= link_to user.followings.count, user_followings_path(user) %></th>
  </tr>
  <tr>
	  <th>followers</th>
	  <th><%= link_to user.followers.count, user_followers_path(user) %></th>
  </tr>
</table>

<div class='row'>
  <% if user.id == current_user.id %>
    <%= link_to '',edit_user_path(user),class: "btn btn-outline-secondary btn-block fas fa-user-cog edit_user_#{user.id}" %>
  <% else %>
    <% if current_user.following?(user) %>
      <%= link_to 'フォロー外す', user_relationships_path(user.id), method: :delete, class: 'btn btn-info' %>
      <%= link_to 'chatを始める', message_path(user.id), method: :get, class: 'm-auto' %>
    <% else %>
      <%= link_to 'フォローする', user_relationships_path(user.id), method: :post, class: 'btn btn-success' %>
    <% end %>
  <% end %>
</div>

app/views/users/_search.html.erb
<h4>検索結果</h4>
<table class='table table-bordered'>
  <thead>
    <tr>
      <th>投稿数</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <td><%= @count_book %></td>
    </tr>
  </tbody>
</table>

app/views/users/edit.html.erb
<div class='container'>
  <div class='row'>
    <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>User info</h2>
    <%= form_with model:@user, local:true do |f| %>
      <%= render 'layouts/errors', obj: @user %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: "form-control name" %>
      </div>
     <div class="form-group">
        <%= f.label :image %>
        <%= f.attachment_field :profile_image, class: "form-control-file user_image" %>
      </div>
      <div class="form-group">
        <%= f.label :introduction %>
        <%= f.text_area :introduction, class: "form-control introduction" %>
      </div>
      <div class="form-group">
        <%= f.submit class: 'btn btn-secondary' %>
      </div>
    <% end %>
    <%= link_to 'アカウントを削除', user_path(@user), method: :delete, data: { confirm: '本当に消しますか？' } %>
  </div>
</div>

app/views/users/index.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: current_user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Users</h2>
      <%= link_to 'グループを作成する', new_group_path, group: Group.new %> |
      <%= link_to 'グループ一覧', groups_path, groups: @groups %>
      <%= render 'index',users: @users %>
    </div>
  </div>
</div>

app/views/users/search.js.erb
$('#count_book_table').html("<%= j(render 'search', locals: {count_book: @count_book}) %>");

app/views/users/show.html.erb
<div class='container px-5 px-sm-0'>
  <div class='row'>
    <div class='col-md-3'>
      <h2>User info</h2>
      <%= render 'info', user: @user %>
      <h2 class="mt-3">New book</h2>
      <%= render 'books/form', book: @book %>
    </div>
    <div class='col-md-8 offset-md-1'>
      <h2>Books</h2>
      <%= render 'books/index',books: @books %>
      <h2>投稿数の前日比・前週比</h2>
      <%= render 'count1'%>
      <h2>7日間分の投稿数</h2>
      <%= render 'count2', books: @books %>
      <canvas id="myLineChart"></canvas>
        <script>
            $(document).on('turbolinks:load', function() {
            var ctx = document.getElementById("myLineChart");
            var myLineChart = new Chart(ctx, {
              type: 'line',
              data: {
                labels: ['6日前', '5日前', '4日前', '3日前', '2日前', '1日前', '今日'],
                datasets: [
                  {
                    label: '投稿した本の数',
                    data: <%= @books.book_count %>,
                    borderColor: "rgba(0,0,255,1)",
                    backgroundColor: "rgba(0,0,0,0)"
                  }
                ],
              },
              options: {
                title: {
                  display: true,
                  text: '7日間の投稿数の比較'
                }
              },
            });
          });
        </script>
        <div class="form-group mt-3">
          <%= form_with url: user_search_path(@user), method: :get do |f| %>
            <%= f.date_field :date %>
            <%= f.submit '検索' %>
          <% end %>
        </div>
        <div id="count_book_table">
          <% if @count_book.present? %>
            <%= render 'count_book', count_book: @count_book %>
          <% end %>
        </div>
    </div>
  </div>
</div>